### PR TITLE
Fix code in error responses

### LINKED ISSUE #6: Add helper/util method for rendering an object's errors?
It's very common to see a pattern like this in a Rails controller (I'm using `jsonapi-utils` methods in the code):

```ruby
if model.save
  jsonapi_render json: model
else
  jsonapi_render json: model.errors # doesn't work
end
```
Seems like this gem should expose a helper for this type of failed `POST` request, e.g. `jsonapi_render_unprocessable model.errors` which would serve `422` response with a response body listing the reasons why the `model` couldn't be written to the DB.

Not sure what JSONAPI spec says about this, however...

### LINKED ISSUE #17: Error codes must be strings
According to the [spec](http://jsonapi.org/format/#error-objects), `code`s in the [exceptions](https://github.com/b2beauty/jsonapi-utils/blob/master/lib/jsonapi/utils/exceptions.rb) must be strings. Currently generated errors aren't  valid against the [JSON API Schema](http://jsonapi.org/schema). See https://github.com/cerebris/jsonapi-resources/issues/675. An example:
```json
{
  "errors": [
    {
      "title": "Bad Request",
      "detail": "This request is not supported.",
      "code": 400,
      "status": "400"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by tiagopog**
It fixes #17  and closes #6.

## Summary

This PR brings:
  - [x] Better error responses now fully compliant with [JSON API's error specs](http://jsonapi.org/format/#errors);
  - [x] New method `JSONAPI::Utils#jsonapi_render_errors` with the capability of rendering errors from exceptions, ActiveRecord objects and Hashes;
  - [x] Better test coverage;
  - [ ] Examples and other improvements in README. 

## Examples
**Code:**
```ruby
# app/controllers/users_controller.rb
  # POST /users
  def create
    user = User.new(user_params)
    if user.save
      jsonapi_render json: user, status: :created
    else
      jsonapi_render_errors json: user, status: :unprocessable_entity
    end
  end

  # PATCH /users/:id
  def update
    user = User.find(params[:id])
    if user.update(user_params)
      jsonapi_render json: user
    else
      jsonapi_render_errors Exceptions::MyCustomError.new(user)
    end
  end

# app/controllers/posts_controller.rb
  # POST /posts
  def create
    post = Post.new(post_params)
    if post.save
      jsonapi_render json: post, status: :created
    else
      errors = [{ id: 'validation', title: 'Something went wrong', code: '100' }]
      jsonapi_render_errors json: errors, status: :unprocessable_entity
    end
  end
```
**Responses:**

Endpoint:

`GET http://localhost:3000/users?fields[foo]=bar&fields[foobar]=bar&include=bar`

Response body:

```json
{
  "errors": [
    {
      "title": "Invalid resource",
      "detail": "foo is not a valid resource.",
      "code": "101",
      "status": "400"
    },
    {
      "title": "Invalid resource",
      "detail": "foobar is not a valid resource.",
      "code": "101",
      "status": "400"
    },
    {
      "title": "Invalid field",
      "detail": "bar is not a valid relationship of users",
      "code": "112",
      "status": "400"
    }
  ]
}
```
--
Endpoint:

`POST http://localhost:3000/users`

Request body:

```json
{
  "data": {
    "type": "users",
    "attributes": {
      "first_name": "",
      "last_name": ""
    }
  }
}
```

Response body:

```json
{
  "errors": [
    {
      "title": "First name can't be blank",
      "id": "first_name",
      "code": "100",
      "status": "422"
    },
    {
      "title": "Last name can't be blank",
      "id": "last_name",
      "code": "100",
      "status": "422"
    }
  ]
}
```

### CODE REVIEW

**Comment by tiagopog** [comment]
:shipit:? @mecampbellsoup @halilim

**Comment by mecampbellsoup** [comment]
LGTM 👍

**Comment by tiagopog** [comment]
@halilim:
screen shot 2016-06-06 at 7 35 08 pm

**Comment by halilim** [comment]
👍

**Comment by tiagopog** [comment]
I will merge the changes and release the patch. Thanks folks.

**Pull request merged**
