### PR TITLE
Feature/refactor render not found

### PR DESCRIPTION
**Pull request by tiagopog**
Closes #7 

## Feature

Besides the integer ones, when a record is not found, it's now able to grab other kinds of resource identifier like `uid` and `slug`.

### Integers

- Not found `:id`:
screen shot 2016-04-17 at 1 26 13 pm

- Not found `:user_id`:
screen shot 2016-04-17 at 2 03 35 pm

### UID

- Not found `:id`:
screen shot 2016-04-17 at 2 03 53 pm

- Not found `:user_id`:
screen shot 2016-04-17 at 2 03 19 pm

### Slug

- Not found `:id`:
screen shot 2016-04-17 at 2 04 32 pm

- Not found `:user_id`:
screen shot 2016-04-17 at 3 29 25 pm

### CODE REVIEW

**Comment by tiagopog** [comment]
:shipit:? @mecampbellsoup

**Comment by mecampbellsoup** [comment]
I can't get the tests to run actually. There were some fixes for Rails 5 in
the JSON API resources gem that aren't included in a gem release yet...
Guess I'll just need to make sure I'm using Rails 4.x locally where I'm
working on this PR locally.

Is CI setup?

**Comment by tiagopog** [comment]
Yep, Codeship for now. On Travis I can see that things are working properly
with MRI 2.2, but I still need to check 2.0 and 2.1.

On Sunday, 17 April 2016, Matt Campbell <notifications@github.com> wrote:

> I can't get the tests to run actually. There were some fixes for Rails 5 in
> the JSON API resources gem that aren't included in a gem release yet...
> Guess I'll just need to make sure I'm using Rails 4.x locally where I'm
> working on this PR locally.
>
> Is CI setup?
>
> On Mon, Apr 18, 2016, 1:32 AM Tiago Guedes <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > [image: :shipit:]? @mecampbellsoup <https://github.com/mecampbellsoup>
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/b2beauty/jsonapi-utils/pull/8#issuecomment-211077407
> >
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/b2beauty/jsonapi-utils/pull/8#issuecomment-211151840>
>


-- 
Tiago Guedes
+55 41 9278 4005

**Comment by tiagopog** [comment]
It worked properly with Rails 4.x. There are no tests running on our CI for
Rails 5 yet.

On Sunday, 17 April 2016, Tiago Guedes <tiagopog@gmail.com> wrote:

> Yep, Codeship for now. On Travis I can see that things are working
> properly with MRI 2.2, but I still need to check 2.0 and 2.1.
>
> On Sunday, 17 April 2016, Matt Campbell <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I can't get the tests to run actually. There were some fixes for Rails 5
>> in
>> the JSON API resources gem that aren't included in a gem release yet...
>> Guess I'll just need to make sure I'm using Rails 4.x locally where I'm
>> working on this PR locally.
>>
>> Is CI setup?
>>
>> On Mon, Apr 18, 2016, 1:32 AM Tiago Guedes <notifications@github.com>
>> wrote:
>>
>> > [image: :shipit:]? @mecampbellsoup <https://github.com/mecampbellsoup>
>> >
>> > —
>> > You are receiving this because you were mentioned.
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/b2beauty/jsonapi-utils/pull/8#issuecomment-211077407>
>> >
>>
>> —
>> You are receiving this because you were assigned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/b2beauty/jsonapi-utils/pull/8#issuecomment-211151840>
>>
>
>
> --
> Tiago Guedes
> +55 41 9278 4005
>
>
>

-- 
Tiago Guedes
+55 41 9278 4005

**Comment by mecampbellsoup** [comment]
@tiagopog so [here is the bug that was patched](https://github.com/cerebris/jsonapi-resources/pull/642) in `jsonapi-resources` master (not yet cut in a release of the gem, however).

When I check my local bundle, it reports using Rails version 4.2.6:

```bash
 ❯ bundle show rails                                                                                                                               [09:43:02]
/Users/mec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rails-4.2.6
```

Oof, I just realized I need to run `bundle exec rspec` instead of `rspec`... rookie mistake! 😆 

Will get some specs written and push a commit ASAP.

**Comment by mecampbellsoup** [comment]
@tiagopog can I get access to view the Code Climate builds please? https://www.dropbox.com/s/knzc15goq671n43/Screenshot%202016-04-18%2009.50.42.png?dl=0

**Comment by tiagopog** [comment]
Did you mean Codeship? I just sent you an invitation.

**Comment by mecampbellsoup** [comment]
LGTM :+1:

**Comment by tiagopog** [comment]
Thanks, @mecampbellsoup :-)

**Comment by mecampbellsoup** [comment]
@tiagopog where are the specs? I thought I saw some new specs for this behavior at one time...

**Comment by tiagopog** [comment]
@mecampbellsoup: https://github.com/b2beauty/jsonapi-utils/blob/master/spec/controllers/posts_controller_spec.rb#L57

**Pull request merged**
